---
- hosts: all
  become: true
  tasks:

    - name: update repository index
      apt:
        update_cache: yes

    - name: install apache2 package
      apt:
        name: apache2
        state: latest

    - name: can be any name  Add hp support for appache
      apt:
        name: libapache2-mod-php
        state: latest



# when statement
# when: ansible_distibution == "ubuntu"
# add to each play, name: refers to a play name
# run playbook on certain distros
# report will indicte fail
# you can add multiple distros
# when: ansible_distibution == ["Debian", "Ubuntu"}
