---
- hosts: all
  become: true
  tasks:

    - name: install twoor more packages
      apt:
        name: 
          - apache2
          - libapache2-mod-php
        state: latest
        update_cache: yes
    


# when statement
# when: ansible_distibution == "ubuntu"
# add to each play, name: refers to a play name
# run playbook on certain distros
# report will indicte fail
# you can add multiple distros
# when: ansible_distibution == ["Debian", "Ubuntu"}
